kind: pipeline
type: docker
name: testing

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: yamllint 
    image: cytopia/yamllint
    pull: if-not-exists
    commands:
      - yamllint -d .yamllint.config *.yaml automations/*.yaml
  - name: home assistant config test
    image: homeassistant/home-assistant:latest
    pull: if-not-exists
    commands:
      - mv geolocation-drone.yaml geolocation.yaml
      - mv configuration-drone.yaml configuration.yaml
      - python -m homeassistant --script check_config --config .
  - name: findmissing
    image: findmissing
    pull: if-not-exists 
    settings:
      HASS_SERVER:
        from_secret: HASS_SERVER
      HASS_TOKEN:
        from_secret: HASS_TOKEN
    commands:
      - cd automations 
      - python3 find_missing.py
  - name: reload automations
    image: kuchel77/drone-webhook #note this is a build of the webhook image that doesn't send a body request
    pull: never
    settings:
      bearer:
        from_secret: HASS_TOKEN
      urls: http://hassio:8123/api/services/automation/reload
      debug: true
    failure: ignore
  - name: notify
    image: plugins/slack
    settings:
      webhook: 
      channel: general
      icon_url: https://unsplash.it/256/256/?random
      template: >
        {{#success build.status}}
          Home Assistant - Build {{build.number}} succeeded. Good job.
        {{else}}
          Home Assistant - Build {{build.number}} failed. Fix me please.
        {{/success}} 
      username: drone
    when:
      status: [ success, failure ]
  - name: send
    image: plugins/webhook #runs an automation depending on the build status. Changes light letting me know if it works
    settings:
      urls:
        - http://hassio:8123/api/webhook/drone_build
      content_type: application/json
      template: |
        { "repo": "{{ repo.name }}", "status": "{{ build.status }}"}
      debug: true
    when:
      status: [success, failure]
